# These are supported funding platforms; fill in only the ones that actually apply.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [learninghub44]
# patreon: 
# ko_fi: 
# custom: "https://paystack.shop/pay/dzio0eaefa"
